IF EXISTS(
	SELECT * 
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CLIENTS'
	)
	BEGIN
		DROP TABLE CLIENTS

END
CREATE TABLE clients(
	CLIENT_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CLIENT NVARCHAR (200) NULL,
	POC NVARCHAR (100) NULL,
	CONTACT_INFO NVARCHAR (2000) NULL,
	EMAIL NVARCHAR (200) NULL,

)
